export const SUPPORTED_LANGUAGES = [
  { label: 'Español', code: 'es' },
  { label: 'Inglés', code: 'en' },
  { label: 'Francés', code: 'fr' },
  { label: 'Alemán', code: 'de' },
  { label: 'Italiano', code: 'it' },
  { label: 'Portugués', code: 'pt' },
  { label: 'Japonés', code: 'ja' },
  { label: 'Coreano', code: 'ko' },
  { label: 'Mandarín', code: 'zh' },
  { label: 'Ruso', code: 'ru' },
  { label: 'Árabe', code: 'ar' },
  { label: 'Hebreo', code: 'he' },
  { label: 'Hindi', code: 'hi' },
  { label: 'Bengalí', code: 'bn' },
  { label: 'Urdu', code: 'ur' },
  { label: 'Swahili', code: 'sw' },
  { label: 'Suajili', code: 'sw' },
  { label: 'Afrikaans', code: 'af' },
  { label: 'Chino', code: 'zh' },
  { label: 'Neerlandés', code: 'nl' },
];
